# Generated by Django 4.2.5 on 2023-09-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_city_city_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='city',
            name='unique city',
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('country', 'name'), name='unique city'),
        ),
    ]
