# Generated by Django 6.0.5 on 2026-06-28 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.country')),
                ('user_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField()),
                ('booking_time', models.DateTimeField()),
                ('guest', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.userdetail')),
                ('house', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='residence.house')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('beds', models.IntegerField()),
                ('has_ac', models.BooleanField(default=False)),
                ('price_per_day', models.FloatField()),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('house', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='residence.house')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_from', models.DateField()),
                ('book_to', models.DateField()),
                ('price', models.FloatField(default=None)),
                ('user_detail', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.userdetail')),
                ('house', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='residence.house')),
                ('room', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='residence.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=None)),
                ('start_date', models.DateField(default=None)),
                ('end_date', models.DateField(default=None)),
                ('booking', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='residence.booking')),
                ('room', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='residence.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomUnavailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_day', models.DateField()),
                ('to_day', models.DateField()),
                ('booked', models.BooleanField(default=False)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residence.house')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residence.room')),
            ],
            options={
                'ordering': ['room', 'from_day'],
            },
        ),
        migrations.AddConstraint(
            model_name='house',
            constraint=models.UniqueConstraint(fields=('user_detail', 'name'), name='Unique House'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('name', 'house'), name='Unique Room'),
        ),
    ]
