# Generated by Django 4.2.5 on 2023-09-07 17:21

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('test_Field', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.country')),
                ('user_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('beds', models.IntegerField()),
                ('has_ac', models.BooleanField(default=False)),
                ('price', models.FloatField()),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residence.house')),
            ],
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None)),
                ('book_from', models.DateField()),
                ('book_to', models.DateField()),
                ('booking_time', models.DateTimeField()),
                ('bill', models.FloatField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userdetail')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residence.house')),
            ],
        ),
        migrations.CreateModel(
            name='RoomAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avail_from', models.DateField()),
                ('avail_to', models.DateField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residence.house')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residence.room')),
            ],
            options={
                'ordering': ['room', 'avail_from'],
            },
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('name', 'house'), name='Unique House'),
        ),
        migrations.AddConstraint(
            model_name='house',
            constraint=models.UniqueConstraint(fields=('user_detail', 'name'), name='Unique Room'),
        ),
    ]
