# Generated by Django 4.2.5 on 2023-09-08 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('residence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='test_Field',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='book_from',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='book_to',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='booking_time',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='house',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='rooms',
        ),
        migrations.AddField(
            model_name='roombooking',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='residence.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='house',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='residence.house'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_from', models.DateField()),
                ('book_to', models.DateField()),
                ('total_price', models.FloatField()),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.userdetail')),
                ('house', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='residence.house')),
            ],
        ),
        migrations.AddField(
            model_name='roombooking',
            name='booking',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='residence.booking'),
        ),
    ]
