# Generated by Django 4.2.5 on 2023-09-09 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('residence', '0002_remove_house_test_field_remove_roombooking_bill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='price',
            field=models.FloatField(default=None),
        ),
        migrations.CreateModel(
            name='RoomCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avail_from', models.DateField(default=None)),
                ('avail_to', models.DateField(default=None)),
                ('price', models.FloatField(default=None)),
                ('room', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='residence.room')),
                ('user_detail', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.userdetail')),
            ],
        ),
    ]
