# Generated by Django 4.2.5 on 2023-09-10 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0003_roombooking_price_roomcart'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomUnavailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_day', models.DateField()),
                ('to_day', models.DateField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residence.house')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residence.room')),
            ],
            options={
                'ordering': ['room', 'from_day'],
            },
        ),
        migrations.RemoveField(
            model_name='roomcart',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roomcart',
            name='user_detail',
        ),
        migrations.DeleteModel(
            name='RoomAvailable',
        ),
        migrations.DeleteModel(
            name='RoomCart',
        ),
    ]
