# Generated by Django 4.2.5 on 2023-09-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0005_cart'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('user_detail', 'room'), name='Unique Cart'),
        ),
    ]
