# Generated by Django 4.2.5 on 2023-09-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0008_roomunavailable_booked'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cart',
            name='Unique Cart',
        ),
        migrations.RemoveConstraint(
            model_name='house',
            name='Unique Room',
        ),
        migrations.RemoveConstraint(
            model_name='room',
            name='Unique House',
        ),
        migrations.RenameField(
            model_name='roombooking',
            old_name='price',
            new_name='price_per_day',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='book_from',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='book_to',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
        migrations.AddField(
            model_name='cart',
            name='price_per_day',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='end_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='start_date',
            field=models.DateField(default=None),
        ),
        migrations.AddConstraint(
            model_name='house',
            constraint=models.UniqueConstraint(fields=('user_detail', 'name'), name='Unique House'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('name', 'house'), name='Unique Room'),
        ),
    ]
