# Generated by Django 4.2.5 on 2023-09-21 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0009_remove_cart_unique_cart_remove_house_unique_room_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='price_per_day',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='price',
            new_name='price_per_day',
        ),
        migrations.RenameField(
            model_name='roombooking',
            old_name='price_per_day',
            new_name='price',
        ),
    ]
